#!/usr/bin/env python3
"""Calculation report generator: collects the tool outputs of a project into one Markdown (+ HTML) report.

Inputs (any subset; sections without data are skipped):
  --model     form-finding JSON (form_find_fdm.py)
  --cases     load-case envelope JSON (run_cases.py *_envelope.json)
  --material  membrane library key (membrane-fabric/reference/materials.json) for the membrane check
  --method    membrane design basis: factor | fm | japan | partial
  --cables    cable schedule CSV (cable_schedule.py)
  --patterns  cutting-pattern CSV (cutting_pattern.py)
  --nest      nesting CSV (nest_panels.py) — listed only
  --extra     free text / Markdown file appended (e.g. steel, connection, foundation tool outputs)
  --precedents  precedents.json files of the connection-precedents skill (gate status, concept, verification)
  --validation  append the validation matrix of the tool set (validate_all.py)

Always included: design basis with every code factor and its V/C/U status, a list of the
unverified factors, model limitations and the governing utilisations found in the data.

Example
  python3 report.py --title "Demo sail" --model sail.json --cases sail_cases_envelope.json \
      --material PVC-III --cables sail_cables.csv --patterns sail_patterns.csv --out sail_report
"""
from __future__ import annotations

import argparse
import csv
import html
import json
import os
import sys
from datetime import date

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
sys.path.insert(0, os.path.join(HERE, "..", "..", "membrane-fabric", "scripts"))
import factors as CF  # noqa: E402


def table(headers, rows):
    out = ["| " + " | ".join(headers) + " |", "|" + "---|" * len(headers)]
    for r in rows:
        out.append("| " + " | ".join("" if v is None else ((f"{v:.3g}" if abs(v) > 1e-9 else "0") if isinstance(v, float)
                                                           else str(v)) for v in r) + " |")
    return "\n".join(out)


def read_csv(path):
    with open(path) as fh:
        return list(csv.DictReader(fh))


def build(a):
    md = [f"# {a.title} — structural calculation report (tensile structure)", "",
          f"Date {date.today().isoformat()} · generated by `tensile-structures/scripts/report.py` · "
          f"factor file: {os.environ.get('TENSILE_FACTORS') or 'defaults'}", ""]
    governing = []

    # 1 design basis
    md += ["## 1. Design basis and code factors", "",
           "Every value below comes from the factor register. **V** = confirmed from a named source, "
           "**C** = code recommended value (National Annex may differ), **U** = unverified, must be confirmed before "
           "issue.", ""]
    rows, unver = [], []
    for path, e in CF.iter_entries(CF.load()):
        rows.append((path, e.get("value", "(table)"), e["status"], e.get("source", "")[:90]))
        if e["status"] == "U":
            unver.append(path)
    md += [table(["factor", "value", "status", "source"], rows), ""]
    md += [f"**Unverified factors ({len(unver)}):** " + (", ".join(f"`{u}`" for u in unver) or "none") + "", ""]

    # 2 form finding
    if a.model:
        with open(a.model) as fh:
            m = json.load(fh)
        ms = m.get("membrane_stress", {})
        md += ["## 2. Geometry and form finding", "",
               f"Type **{m.get('type', 'custom')}**, {len(m['nodes'])} nodes, {len(m['edges'])} links, surface area "
               f"{m.get('surface_area_m2', 0):.2f} m². Method: {m.get('solver', {}).get('method', 'FDM')}.", ""]
        if ms:
            md += [f"Prestress (grid estimate): mean {ms['mean']:.2f}, min {ms['min']:.2f}, max {ms['max']:.2f} kN/m.", ""]
        if m.get("cable_groups"):
            md += [table(["cable group", "F max kN", "chord m", "sag m", "sag/chord", "mid dz m"],
                         [(g["group"], g["force_max"], g.get("chord"), g.get("sag"), g.get("sag_ratio"), g.get("mid_dz"))
                          for g in m["cable_groups"]]), ""]
        if m.get("support_groups"):
            md += [table(["support group", "|F| kN", "Fz kN", "line load kN/m"],
                         [(k, v["magnitude"], v["pull"][2], v.get("line_load_kN_m")) for k, v in m["support_groups"].items()]), ""]
        elif m.get("reactions"):
            md += [table(["support node", "Fx", "Fy", "Fz", "|F| kN"],
                         [(r["node"], *r["pull"], r["magnitude"]) for r in m["reactions"][:20]]), ""]

    # 3 load cases
    env = None
    if a.cases:
        with open(a.cases) as fh:
            env = json.load(fh)
        md += ["## 3. Load cases (non-linear, solved separately)", "",
               table(["case", "factor", "duration", "max disp mm", "warp max", "weft max", "cable max", "cable min",
                      "slack/wrinkled", "ponding"],
                     [(r["case"], r["factor"], r.get("duration"), r["max_disp_mm"], r.get("warp_max"), r.get("weft_max"),
                       r["cable_max"], r["cable_min"], r["slack_links"], r["ponding"]) for r in env["summary"]]), "",
               "Cable groups (envelope):", "",
               table(["group", "F max kN", "case", "F min kN", "case"],
                     [(g, v["max"], v["case_max"], v["min"], v["case_min"]) for g, v in sorted(env["groups"].items())]), "",
               "Supports (max resultant):", "",
               table(["node", "|F| kN", "case", "Fz min", "Fz max"],
                     [(n, v["magnitude"], v["case"], v["Fz_min"], v["Fz_max"])
                      for n, v in sorted(env["reaction_envelope"].items(), key=lambda kv: int(kv[0]))]), ""]
        if any(r["cable_min"] is not None and r["cable_min"] <= 0 for r in env["summary"]):
            md += ["**WARNING:** slack cable segments in at least one case.", ""]
        if any(r["ponding"] not in ("-", "no basin (surface drains)") for r in env["summary"]):
            md += ["**FAIL:** ponding detected — revise curvature/prestress/drainage.", ""]

    # 4 membrane check
    if a.material and env:
        import membrane_check as MCK
        lib = MCK.load_lib()
        mat = lib["materials"][a.material]
        seam = CF.get("membrane.seam_efficiency")
        rows_m = []
        worst = 0.0
        for r in env["summary"]:
            case = "prestress" if r["case"].upper() in ("PS", "PRESTRESS") else (
                "wind" if r.get("duration") == "short" else "snow")
            combo = "P+D" if case == "prestress" else ("P+D+W" if case == "wind" else "P+D+S")
            aw, basis = MCK.allowable(mat["fw"], a.method, case, mat["family"], fm_combo=combo)
            af, _ = MCK.allowable(mat["ff"], a.method, case, mat["family"], fm_combo=combo)
            u = max((r.get("warp_max") or 0) / aw, (r.get("weft_max") or 0) / af) / seam
            worst = max(worst, u)
            rows_m.append((r["case"], r.get("warp_max"), r.get("weft_max"), aw, af, u, basis))
        governing.append(("membrane (seams)", worst))
        md += [f"## 4. Membrane check — {a.material} ({mat['family']}, fw/ff = {mat['fw']}/{mat['ff']} kN/m, "
               f"{mat['status']}), method `{a.method}`, seam efficiency {seam}", "",
               table(["case", "warp", "weft", "n_all warp", "n_all weft", "util (seam)", "basis"], rows_m), ""]
        if a.method != "partial" and any(abs(r.get("factor", 1) - 1) > 1e-9 for r in env["summary"]):
            md += ["Note: factored load cases combined with a global stress-factor method count safety twice "
                   "(conservative).", ""]

    # 5 cables
    if a.cables:
        rows_c = read_csv(a.cables)
        u = [float(r["util_EN"]) for r in rows_c if r.get("util_EN")]
        if u:
            governing.append(("cables (EN 1993-1-11)", max(u)))
        md += ["## 5. Cable schedule and checks", "",
               table(["ID", "type", "Ø", "F_Rd kN", "F_ULS kN", "util EN", "util ASCE", "L0 pin unstressed m", "end A", "end B"],
                     [(r["id"], r["type"], r["d_mm"], r["F_Rd_kN"], r["F_ULS_kN"], r["util_EN"], r["util_ASCE"],
                       r["L0_pin_unstressed_Tref_m"], r["end_A"], r["end_B"]) for r in rows_c]), ""]

    # 6 patterns
    if a.patterns:
        rows_p = read_csv(a.patterns)
        md += ["## 6. Cutting patterns", "",
               table(["panel", "L mm", "W mm", "fits roll", "net m²", "strain max %", "left", "right"],
                     [(r["panel"], r["length_mm"], r["width_mm"], r["fits_roll"], r["net_area_m2"],
                       r["flatten_strain_max_%"], r["left"], r["right"]) for r in rows_p]), ""]
        if any(r["fits_roll"] == "False" for r in rows_p):
            md += ["**WARNING:** panels wider than the roll — use `--auto-split` or narrower strips.", ""]
    if a.nest:
        rows_n = read_csv(a.nest)
        md += [f"Nesting: {len(rows_n)} panels placed (see nested DXF).", ""]

    if a.precedents:
        sys.path.insert(0, os.path.join(HERE, "..", "..", "connection-precedents", "scripts"))
        import precedent_search as PS  # noqa: E402
        md += ["## 7a. Connection precedents (searched before design)", ""]
        rows = []
        for f in a.precedents:
            with open(f) as fh:
                d = json.load(fh)
            ok, res = PS.gate(d, base_dir=os.path.dirname(os.path.abspath(f)))
            viewed = sum(1 for p in d.get("precedents", []) if p.get("viewed"))
            rows.append((d.get("node", "?"), len(d.get("precedents", [])), viewed, "PASS" if ok else "FAIL",
                         (d.get("concept") or {}).get("summary", "")[:120]))
            if not ok:
                governing.append((f"precedent gate {d.get('node', '?')}", 9.99))
        md += [table(["node", "pins", "viewed", "gate", "concept"], rows), ""]
        for f in a.precedents:
            with open(f) as fh:
                d = json.load(fh)
            if d.get("verification"):
                md += [f"Verification ({d.get('node', '?')}):", ""] + [f"- {v}" for v in d["verification"]] + [""]

    if a.extra:
        with open(a.extra) as fh:
            md += ["## 7. Further checks (steel, connections, foundations)", "", "```", fh.read().rstrip(), "```", ""]

    if a.validation:
        import validate_all as VA  # noqa: E402
        vm = VA.render(VA.matrix())
        md += ["## 8. Validation of the tools", ""] + vm.split("\n")[2:] + [""]

    md += ["## Governing utilisations", ""]
    md += [table(["item", "max utilisation", "status"], [(k, v, "OK" if v <= 1 else "NOT OK") for k, v in governing])
           if governing else "No utilisations found in the supplied data.", ""]
    md += ["## Limitations", "",
           "- Form finding: force density method (geometry of the prestress state); load analysis: cable-net analogy "
           "or orthotropic CST membrane with tension-field wrinkling (see `analysis` metadata).",
           "- Linear-orthotropic fabric, no creep; wind as quasi-static pressure fields (no aeroelastic response).",
           "- Code values marked U must be confirmed against the standard edition and National Annex in force.",
           "- This report supports, and does not replace, the design and independent check by a qualified engineer.", ""]
    return "\n".join(md), governing


def to_html(md, title):
    lines = md.split("\n")
    out = [f"<!doctype html><html><head><meta charset='utf-8'><title>{html.escape(title)}</title>",
           "<style>body{font-family:system-ui,sans-serif;max-width:1100px;margin:2em auto;padding:0 16px;line-height:1.45}"
           "table{border-collapse:collapse;font-size:13px;margin:.6em 0}td,th{border:1px solid #bbb;padding:3px 7px}"
           "th{background:#eef}code{background:#f4f4f4;padding:0 3px}pre{background:#f7f7f7;padding:8px;overflow:auto}</style>"
           "</head><body>"]
    i = 0
    in_pre = False
    while i < len(lines):
        ln = lines[i]
        if ln.startswith("```"):
            out.append("</pre>" if in_pre else "<pre>")
            in_pre = not in_pre
        elif in_pre:
            out.append(html.escape(ln))
        elif ln.startswith("|") and i + 1 < len(lines) and lines[i + 1].startswith("|---"):
            hdr = [c.strip() for c in ln.strip("|").split("|")]
            out.append("<table><tr>" + "".join(f"<th>{html.escape(h)}</th>" for h in hdr) + "</tr>")
            i += 2
            while i < len(lines) and lines[i].startswith("|"):
                cells = [c.strip() for c in lines[i].strip("|").split("|")]
                out.append("<tr>" + "".join(f"<td>{html.escape(c)}</td>" for c in cells) + "</tr>")
                i += 1
            out.append("</table>")
            continue
        elif ln.startswith("# "):
            out.append(f"<h1>{html.escape(ln[2:])}</h1>")
        elif ln.startswith("## "):
            out.append(f"<h2>{html.escape(ln[3:])}</h2>")
        elif ln.startswith("- "):
            out.append(f"<li>{html.escape(ln[2:])}</li>")
        elif ln.strip():
            t = html.escape(ln).replace("**", "")
            out.append(f"<p>{t}</p>")
        i += 1
    out.append("</body></html>")
    return "\n".join(out)


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--title", default="Tensile structure")
    ap.add_argument("--model")
    ap.add_argument("--cases")
    ap.add_argument("--material")
    ap.add_argument("--method", default="factor", choices=["factor", "fm", "japan", "partial"])
    ap.add_argument("--cables")
    ap.add_argument("--patterns")
    ap.add_argument("--nest")
    ap.add_argument("--extra")
    ap.add_argument("--precedents", nargs="*", help="precedents.json files (connection-precedents skill)")
    ap.add_argument("--validation", action="store_true", help="append the validation matrix")
    ap.add_argument("--factors", default=None)
    ap.add_argument("--out", default="report")
    a = ap.parse_args(argv)
    if a.factors:
        os.environ["TENSILE_FACTORS"] = a.factors
    md, gov = build(a)
    with open(a.out + ".md", "w") as fh:
        fh.write(md)
    with open(a.out + ".html", "w") as fh:
        fh.write(to_html(md, a.title))
    print(f"Wrote {a.out}.md and {a.out}.html")
    for k, v in gov:
        print(f"  governing {k}: {v:.2f} {'OK' if v <= 1 else 'NOT OK'}")
    return md


if __name__ == "__main__":
    import signal
    if hasattr(signal, "SIGPIPE"):
        signal.signal(signal.SIGPIPE, signal.SIG_DFL)  # quiet exit when piped into head/grep
    main(sys.argv[1:])
